hw_if: hal: Add watchdog interrupt stats
zephyrproject-rtos/nrf_wifi pull request #3
Opened 2024-11-26 08:53 UTC by kapbh

Add watchdog interrupt stats for number of time
interrupt received and ignored.

2024-11-26 08:56 UTC, krish2718 commented on hw_if/hal/inc/hal_structs.h
> +	int watchdog_timer_recieved;
```suggestion
	int wdt_irq_recieved;
```

2024-11-26 09:01 UTC, sachinthegreen requested changes

2024-11-26 09:01 UTC, sachinthegreen commented on hw_if/hal/src/hal_interrupt.c
> +		hal_dev_ctx->wdt_irq_ignored++;
Shouldn't this also be protected with `NRF_WIFI_RPU_RECOVERY_DEBUG` ?

2024-11-26 09:01 UTC, sachinthegreen commented on hw_if/hal/src/hal_interrupt.c
>  		nrf_wifi_osal_log_dbg("Received watchdog interrupt");
Shouldn't both statements above also be protected with `NRF_WIFI_RPU_RECOVERY_DEBUG` ?

2024-11-26 09:07 UTC, kapbh commented on hw_if/hal/inc/hal_structs.h
> +	int watchdog_timer_recieved;
Instead of wdt_irq_received, watchdog_timer_received is better right?

2024-11-26 09:09 UTC, kapbh commented on hw_if/hal/src/hal_interrupt.c
> +		hal_dev_ctx->wdt_irq_ignored++;
It's already in `NRF_WIFI_RPU_RECOVERY_DEBUG`.

2024-11-26 09:16 UTC, kapbh commented on hw_if/hal/src/hal_interrupt.c
>  		nrf_wifi_osal_log_dbg("Received watchdog interrupt");
It should be with `NRF_WIFI_RPU_RECOVERY`.

2024-11-28 13:00 UTC, sachinthegreen approved these changes

2024-11-29 10:28 UTC, krish2718 approved these changes

2024-12-02 08:11 UTC, merged